baseURL = "https://qdriven.github.io/"
languageCode = "en-us"
title = "DirtyHands-Tester"
theme = "mediumish-gohugo-theme"
summaryLength = 5
copyright = "QDriven- All rights reserved"
enableEmoji = true
publishDir = "docs"
#disqusShortname = "your-shortname-here"
#googleAnalytics = "UA-1XXXXXXX1-1"

[params]
  logo = "/images/logos/logo.png"
  description ="Learning from Practice"
  #mailchimp = "you can provide a mailchimp-link here"

[params.author]
  name = "dirty-hands-qa"
  thumbnail = "/images/author.png"
  description = "DirtyHands"

[params.index]
  picture = "/images/author.png"
  title = "Quality is a Long Run"
  subtitle = ""
  mdtext = '''
There is no such thing as perfection, but to improve over the time!
'''
  alertbar = false

[params.social]
  github = "qdriven"

## Main Menu
[[menu.main]]
    name = "All Blogs"
    weight = 100
    identifier = "blog"
    url = "/blog"
[[menu.main]]
    name="api测试-英文"
    weight = 100
    identifier="english"
    url="/tags/english/"
 [[menu.main]]
    name="python-tips"
    weight = 100
    identifier="python-tips"
    url="/tags/python/"
 [[menu.main]]
    name="tips"
    weight = 100
    identifier="tips"
    url="/tags/tips/"
 [[menu.main]]
    name="shell"
    weight = 100
    identifier="shell"
    url="/tags/shell/"