@startuml

class Singleton


class Singleton {
- instance: Singleton
- singleTonData: HashMap
- private Singleton()
+ getInstance(): Singleton
+ singletonMethodA(): void
+ singletonMethodB(): void
}

@enduml